# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 693)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 56, 20))
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(240, 18, 20, 141))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(100, 12, 151, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(261, 10, 56, 20))
        self.label_4.setObjectName("label_4")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(330, 12, 301, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(620, 20, 20, 641))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(490, 150, 141, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(19, 650, 611, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(420, 150, 56, 20))
        self.label_30.setObjectName("label_30")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(10, 20, 20, 641))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(31, 150, 56, 20))
        self.label_43.setObjectName("label_43")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(100, 152, 311, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 40, 363, 102))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_6.addWidget(self.pushButton_17)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_7.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_7.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_7.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_7.addWidget(self.pushButton_15, 2, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_7.addWidget(self.pushButton_16, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_7.addWidget(self.pushButton_12, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 207, 93))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 170, 371, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 0, 364, 451))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem, 3, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_67.setObjectName("label_67")
        self.gridLayout_27.addWidget(self.label_67, 1, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_68.setObjectName("label_68")
        self.gridLayout_27.addWidget(self.label_68, 0, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_69.setObjectName("label_69")
        self.gridLayout_27.addWidget(self.label_69, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem3, 1, 2, 1, 1)
        self.widget_4 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_27.addWidget(self.widget_4, 0, 1, 1, 1)
        self.widget_6 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_27.addWidget(self.widget_6, 1, 1, 1, 1)
        self.widget_8 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_8.setAutoFillBackground(False)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_27.addWidget(self.widget_8, 2, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_27, 0, 2, 1, 1)
        self.line_57 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_57.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.gridLayout_24.addWidget(self.line_57, 2, 1, 1, 1)
        self.line_58 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.gridLayout_24.addWidget(self.line_58, 0, 1, 1, 1)
        self.line_59 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_59.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_59.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_59.setObjectName("line_59")
        self.gridLayout_24.addWidget(self.line_59, 1, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem4 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 3, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_60.setObjectName("label_60")
        self.gridLayout_17.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_61.setObjectName("label_61")
        self.gridLayout_17.addWidget(self.label_61, 2, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_59.setObjectName("label_59")
        self.gridLayout_17.addWidget(self.label_59, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem6, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem7, 0, 2, 1, 1)
        self.widget_9 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_9.setAutoFillBackground(False)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_17.addWidget(self.widget_9, 0, 1, 1, 1)
        self.widget_11 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_11.setAutoFillBackground(False)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_17.addWidget(self.widget_11, 1, 1, 1, 1)
        self.widget_13 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_13.setAutoFillBackground(False)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_17.addWidget(self.widget_13, 2, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_17, 2, 0, 1, 1)
        self.line_56 = QtWidgets.QFrame(self.layoutWidget_6)
        self.line_56.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.gridLayout_24.addWidget(self.line_56, 1, 2, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        spacerItem8 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem8, 3, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_65.setObjectName("label_65")
        self.gridLayout_26.addWidget(self.label_65, 0, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_66.setObjectName("label_66")
        self.gridLayout_26.addWidget(self.label_66, 2, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_64.setObjectName("label_64")
        self.gridLayout_26.addWidget(self.label_64, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem11, 2, 2, 1, 1)
        self.widget_10 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_10.setAutoFillBackground(False)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_26.addWidget(self.widget_10, 0, 1, 1, 1)
        self.widget_12 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_12.setAutoFillBackground(False)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_26.addWidget(self.widget_12, 1, 1, 1, 1)
        self.widget_15 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_26.addWidget(self.widget_15, 2, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_26, 2, 2, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_62.setObjectName("label_62")
        self.gridLayout_25.addWidget(self.label_62, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_25.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_63.setObjectName("label_63")
        self.gridLayout_25.addWidget(self.label_63, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem12, 3, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem13, 1, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem14, 2, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem15, 0, 2, 1, 1)
        self.widget = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.gridLayout_25.addWidget(self.widget, 0, 1, 1, 1)
        self.widget_5 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_25.addWidget(self.widget_5, 1, 1, 1, 1)
        self.widget_7 = DynamicGraphWidget_curve(self.layoutWidget_6)
        self.widget_7.setAutoFillBackground(False)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_25.addWidget(self.widget_7, 2, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 0, 364, 451))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        spacerItem16 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem16, 3, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_70.setObjectName("label_70")
        self.gridLayout_29.addWidget(self.label_70, 1, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_71.setObjectName("label_71")
        self.gridLayout_29.addWidget(self.label_71, 0, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_72.setObjectName("label_72")
        self.gridLayout_29.addWidget(self.label_72, 2, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_29.addItem(spacerItem17, 0, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_29.addItem(spacerItem18, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_29.addItem(spacerItem19, 1, 2, 1, 1)
        self.widget_14 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_14.setAutoFillBackground(False)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_29.addWidget(self.widget_14, 0, 1, 1, 1)
        self.widget_16 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_16.setAutoFillBackground(False)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_29.addWidget(self.widget_16, 1, 1, 1, 1)
        self.widget_17 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_17.setAutoFillBackground(False)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_29.addWidget(self.widget_17, 2, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_29, 0, 2, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.layoutWidget_7)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.gridLayout_28.addWidget(self.line_60, 2, 1, 1, 1)
        self.line_61 = QtWidgets.QFrame(self.layoutWidget_7)
        self.line_61.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_61.setObjectName("line_61")
        self.gridLayout_28.addWidget(self.line_61, 0, 1, 1, 1)
        self.line_62 = QtWidgets.QFrame(self.layoutWidget_7)
        self.line_62.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_62.setObjectName("line_62")
        self.gridLayout_28.addWidget(self.line_62, 1, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem20 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem20, 3, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_73.setObjectName("label_73")
        self.gridLayout_19.addWidget(self.label_73, 0, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_74.setObjectName("label_74")
        self.gridLayout_19.addWidget(self.label_74, 2, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_75.setObjectName("label_75")
        self.gridLayout_19.addWidget(self.label_75, 1, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem21, 1, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem22, 2, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem23, 0, 2, 1, 1)
        self.widget_18 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_18.setAutoFillBackground(False)
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_19.addWidget(self.widget_18, 0, 1, 1, 1)
        self.widget_19 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_19.setAutoFillBackground(False)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_19.addWidget(self.widget_19, 1, 1, 1, 1)
        self.widget_20 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_20.setAutoFillBackground(False)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_19.addWidget(self.widget_20, 2, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        self.line_63 = QtWidgets.QFrame(self.layoutWidget_7)
        self.line_63.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_63.setObjectName("line_63")
        self.gridLayout_28.addWidget(self.line_63, 1, 2, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem24 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem24, 3, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_76.setObjectName("label_76")
        self.gridLayout_30.addWidget(self.label_76, 0, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_77.setObjectName("label_77")
        self.gridLayout_30.addWidget(self.label_77, 2, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_78.setObjectName("label_78")
        self.gridLayout_30.addWidget(self.label_78, 1, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem25, 1, 2, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem26, 0, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem27, 2, 2, 1, 1)
        self.widget_21 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_21.setAutoFillBackground(False)
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_30.addWidget(self.widget_21, 0, 1, 1, 1)
        self.widget_22 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_22.setAutoFillBackground(False)
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_30.addWidget(self.widget_22, 1, 1, 1, 1)
        self.widget_23 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_30.addWidget(self.widget_23, 2, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_30, 2, 2, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_79 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_79.setObjectName("label_79")
        self.gridLayout_31.addWidget(self.label_79, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_36.setObjectName("label_36")
        self.gridLayout_31.addWidget(self.label_36, 1, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_80.setObjectName("label_80")
        self.gridLayout_31.addWidget(self.label_80, 2, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem28, 3, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem29, 1, 2, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem30, 2, 2, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem31, 0, 2, 1, 1)
        self.widget_24 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_24.setAutoFillBackground(False)
        self.widget_24.setObjectName("widget_24")
        self.gridLayout_31.addWidget(self.widget_24, 0, 1, 1, 1)
        self.widget_25 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_25.setAutoFillBackground(False)
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_31.addWidget(self.widget_25, 1, 1, 1, 1)
        self.widget_26 = DynamicGraphWidget_curve(self.layoutWidget_7)
        self.widget_26.setAutoFillBackground(False)
        self.widget_26.setObjectName("widget_26")
        self.gridLayout_31.addWidget(self.widget_26, 2, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_31, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_8.setGeometry(QtCore.QRect(1, 0, 362, 451))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        spacerItem32 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem32, 3, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_81.setObjectName("label_81")
        self.gridLayout_33.addWidget(self.label_81, 1, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_82.setObjectName("label_82")
        self.gridLayout_33.addWidget(self.label_82, 0, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_83.setObjectName("label_83")
        self.gridLayout_33.addWidget(self.label_83, 2, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_33.addItem(spacerItem33, 0, 2, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_33.addItem(spacerItem34, 2, 2, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_33.addItem(spacerItem35, 1, 2, 1, 1)
        self.widget_29 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_29.setAutoFillBackground(False)
        self.widget_29.setObjectName("widget_29")
        self.gridLayout_33.addWidget(self.widget_29, 0, 1, 1, 1)
        self.widget_30 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_30.setAutoFillBackground(False)
        self.widget_30.setObjectName("widget_30")
        self.gridLayout_33.addWidget(self.widget_30, 1, 1, 1, 1)
        self.widget_31 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_31.setAutoFillBackground(False)
        self.widget_31.setObjectName("widget_31")
        self.gridLayout_33.addWidget(self.widget_31, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_33, 0, 2, 1, 1)
        self.line_64 = QtWidgets.QFrame(self.layoutWidget_8)
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_64.setObjectName("line_64")
        self.gridLayout_32.addWidget(self.line_64, 2, 1, 1, 1)
        self.line_65 = QtWidgets.QFrame(self.layoutWidget_8)
        self.line_65.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_65.setObjectName("line_65")
        self.gridLayout_32.addWidget(self.line_65, 0, 1, 1, 1)
        self.line_66 = QtWidgets.QFrame(self.layoutWidget_8)
        self.line_66.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_66.setObjectName("line_66")
        self.gridLayout_32.addWidget(self.line_66, 1, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem36 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem36, 3, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_84.setObjectName("label_84")
        self.gridLayout_18.addWidget(self.label_84, 0, 0, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_85.setObjectName("label_85")
        self.gridLayout_18.addWidget(self.label_85, 2, 0, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_86.setObjectName("label_86")
        self.gridLayout_18.addWidget(self.label_86, 1, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem37, 1, 2, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem38, 2, 2, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem39, 0, 2, 1, 1)
        self.widget_32 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_32.setAutoFillBackground(False)
        self.widget_32.setObjectName("widget_32")
        self.gridLayout_18.addWidget(self.widget_32, 0, 1, 1, 1)
        self.widget_33 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_33.setAutoFillBackground(False)
        self.widget_33.setObjectName("widget_33")
        self.gridLayout_18.addWidget(self.widget_33, 1, 1, 1, 1)
        self.widget_34 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_34.setAutoFillBackground(False)
        self.widget_34.setObjectName("widget_34")
        self.widget_35 = QtWidgets.QWidget(self.widget_34)
        self.widget_35.setGeometry(QtCore.QRect(180, 0, 120, 60))
        self.widget_35.setAutoFillBackground(False)
        self.widget_35.setObjectName("widget_35")
        self.gridLayout_18.addWidget(self.widget_34, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_18, 2, 0, 1, 1)
        self.line_67 = QtWidgets.QFrame(self.layoutWidget_8)
        self.line_67.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_67.setObjectName("line_67")
        self.gridLayout_32.addWidget(self.line_67, 1, 2, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        spacerItem40 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem40, 3, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_87.setObjectName("label_87")
        self.gridLayout_34.addWidget(self.label_87, 0, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_88.setObjectName("label_88")
        self.gridLayout_34.addWidget(self.label_88, 2, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_89.setObjectName("label_89")
        self.gridLayout_34.addWidget(self.label_89, 1, 0, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem41, 1, 2, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem42, 0, 2, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem43, 2, 2, 1, 1)
        self.widget_36 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_36.setAutoFillBackground(False)
        self.widget_36.setObjectName("widget_36")
        self.gridLayout_34.addWidget(self.widget_36, 0, 1, 1, 1)
        self.widget_37 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_37.setAutoFillBackground(False)
        self.widget_37.setObjectName("widget_37")
        self.gridLayout_34.addWidget(self.widget_37, 1, 1, 1, 1)
        self.widget_38 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_38.setObjectName("widget_38")
        self.gridLayout_34.addWidget(self.widget_38, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_34, 2, 2, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_90 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_90.setObjectName("label_90")
        self.gridLayout_35.addWidget(self.label_90, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_37.setObjectName("label_37")
        self.gridLayout_35.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_91.setObjectName("label_91")
        self.gridLayout_35.addWidget(self.label_91, 2, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(120, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem44, 3, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_35.addItem(spacerItem45, 1, 2, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_35.addItem(spacerItem46, 2, 2, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(0, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_35.addItem(spacerItem47, 0, 2, 1, 1)
        self.widget_39 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_39.setAutoFillBackground(False)
        self.widget_39.setObjectName("widget_39")
        self.gridLayout_35.addWidget(self.widget_39, 0, 1, 1, 1)
        self.widget_40 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_40.setAutoFillBackground(False)
        self.widget_40.setObjectName("widget_40")
        self.gridLayout_35.addWidget(self.widget_40, 1, 1, 1, 1)
        self.widget_41 = DynamicGraphWidget_curve(self.layoutWidget_8)
        self.widget_41.setAutoFillBackground(False)
        self.widget_41.setObjectName("widget_41")
        self.gridLayout_35.addWidget(self.widget_41, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_35, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(400, 160, 20, 501))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(440, 170, 181, 431))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 172, 400))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem48 = QtWidgets.QSpacerItem(0, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem48, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(0, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem49, 1, 1, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(160, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem50, 4, 0, 1, 1)
        self.widget_3 = DynamicGraphWidget_angle(self.gridLayoutWidget_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_2 = DynamicGraphWidget_angle(self.gridLayoutWidget_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 3, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 172, 400))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem51 = QtWidgets.QSpacerItem(0, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem51, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(0, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem52, 1, 1, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(160, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem53, 4, 0, 1, 1)
        self.widget_27 = DynamicGraphWidget_veloc(self.gridLayoutWidget_3)
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_3.addWidget(self.widget_27, 1, 0, 1, 1)
        self.widget_28 = DynamicGraphWidget_veloc(self.gridLayoutWidget_3)
        self.widget_28.setObjectName("widget_28")
        self.gridLayout_3.addWidget(self.widget_28, 3, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(530, 610, 93, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">建立连接</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">控制指令</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">机体状态</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">四肢状态</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "一键启动"))
        self.pushButton_2.setText(_translate("MainWindow", "急停"))
        self.pushButton_17.setText(_translate("MainWindow", "报警"))
        self.pushButton_13.setText(_translate("MainWindow", "爬坡"))
        self.pushButton_14.setText(_translate("MainWindow", "越障"))
        self.pushButton_11.setText(_translate("MainWindow", "走"))
        self.pushButton_15.setText(_translate("MainWindow", "跳"))
        self.pushButton_16.setText(_translate("MainWindow", "奔跑"))
        self.pushButton_12.setText(_translate("MainWindow", "小跑"))
        self.pushButton_3.setText(_translate("MainWindow", "姿态参数"))
        self.pushButton_4.setText(_translate("MainWindow", "控制参数"))
        self.pushButton_8.setText(_translate("MainWindow", "显示参数"))
        self.pushButton_5.setText(_translate("MainWindow", "连接"))
        self.pushButton_6.setText(_translate("MainWindow", "断开连接"))
        self.label_2.setText(_translate("MainWindow", "机器人IP"))
        self.label_8.setText(_translate("MainWindow", "运行状态"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Disconnected</p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "RFD"))
        self.label_68.setText(_translate("MainWindow", "RFX"))
        self.label_69.setText(_translate("MainWindow", "RFK"))
        self.label_60.setText(_translate("MainWindow", "LBX"))
        self.label_61.setText(_translate("MainWindow", "LBK"))
        self.label_59.setText(_translate("MainWindow", "LBD"))
        self.label_65.setText(_translate("MainWindow", "RBX"))
        self.label_66.setText(_translate("MainWindow", "RBK"))
        self.label_64.setText(_translate("MainWindow", "RBD"))
        self.label_62.setText(_translate("MainWindow", "LFX"))
        self.label_35.setText(_translate("MainWindow", "LFD"))
        self.label_63.setText(_translate("MainWindow", "LFK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "液压力"))
        self.label_70.setText(_translate("MainWindow", "RFD"))
        self.label_71.setText(_translate("MainWindow", "RFX"))
        self.label_72.setText(_translate("MainWindow", "RFK"))
        self.label_73.setText(_translate("MainWindow", "LBX"))
        self.label_74.setText(_translate("MainWindow", "LBK"))
        self.label_75.setText(_translate("MainWindow", "LBD"))
        self.label_76.setText(_translate("MainWindow", "RBX"))
        self.label_77.setText(_translate("MainWindow", "RBK"))
        self.label_78.setText(_translate("MainWindow", "RBD"))
        self.label_79.setText(_translate("MainWindow", "LFX"))
        self.label_36.setText(_translate("MainWindow", "LFD"))
        self.label_80.setText(_translate("MainWindow", "LFK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "液压缸位移"))
        self.label_81.setText(_translate("MainWindow", "RFY"))
        self.label_82.setText(_translate("MainWindow", "RFX"))
        self.label_83.setText(_translate("MainWindow", "RFZ"))
        self.label_84.setText(_translate("MainWindow", "LBX"))
        self.label_85.setText(_translate("MainWindow", "LBZ"))
        self.label_86.setText(_translate("MainWindow", "LBY"))
        self.label_87.setText(_translate("MainWindow", "RBX"))
        self.label_88.setText(_translate("MainWindow", "RBZ"))
        self.label_89.setText(_translate("MainWindow", "RBY"))
        self.label_90.setText(_translate("MainWindow", "LFX"))
        self.label_37.setText(_translate("MainWindow", "LFY"))
        self.label_91.setText(_translate("MainWindow", "LFZ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "足端力"))
        self.label_10.setText(_translate("MainWindow", "姿态角"))
        self.label_11.setText(_translate("MainWindow", "角速度"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "旋转"))
        self.label_12.setText(_translate("MainWindow", "速度"))
        self.label_13.setText(_translate("MainWindow", "加速度"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "平移"))
        self.pushButton_7.setText(_translate("MainWindow", "IMU标定"))

from plot import DynamicGraphWidget_angle, DynamicGraphWidget_curve, DynamicGraphWidget_veloc
